#!/bin/sh

DOCKER="${DOCKER:-podman}"
IMAGE="${IMAGE:-ghcr.io/ricardobranco777/smeltme:latest}"

if [ "$1" = "--version" ] ; then
	latest=$(curl -s https://api.github.com/repos/ricardobranco777/smeltme/tags | jq -Mr '.[0].name')
	if [ "${latest#v}" != "$("$DOCKER" run --rm "$IMAGE" --version)" ] ; then
		echo "Latest version available: $latest" >&2
	fi
fi

exec "$DOCKER" run --rm -e DEBUG -e BUGZILLA_TOKEN -e JIRA_TOKEN "$IMAGE" "$@"
